# frozen_string_literal: true

namespace :docs do
  desc "Generates Markdown documentation for Pundit policies"
  task pundit: :environment do
    # Use an array to build the output string
    output_lines = []
    output_lines << "# Pundit Policy Documentation"
    output_lines << "This document is auto-generated by `rake docs:pundit`."
    output_lines << "Generated: #{Time.now.strftime('%Y-%m-%d %H:%M:%S')}"
    output_lines << ""

    # Find all policy files
    policy_files = Dir[Rails.root.join("app/policies/*_policy.rb")]

    policy_files.sort.each do |file_path|
      class_name = File.basename(file_path, ".rb").camelize

      # Skip the base class
      next if class_name == "ApplicationPolicy"

      resource_name = class_name.remove("Policy")
      output_lines << "## #{resource_name} Policy (`#{class_name}`)"
      output_lines << ""

      policy_class = class_name.safe_constantize

      unless policy_class
        output_lines << "*Could not load class `#{class_name}` from `#{file_path}`. Skipping.*"
        output_lines << ""
        next
      end

      # Get methods defined on this class (or its included modules), not ancestors
      actions = policy_class.public_instance_methods(false).grep(/\?$/).sort

      if actions.empty?
        output_lines << "*No policy actions (methods ending in `?`) found for this class.*"
        output_lines << ""
        next
      end

      actions.each do |action|
        output_lines << "### `#{action}`"
        output_lines << ""

        begin
          # Get the Method object
          method_obj = policy_class.public_instance_method(action)
          # Find its exact source file and start line
          source_file, start_line = method_obj.source_location

          unless source_file && start_line
            output_lines << "*Could not find source for `#{action}` (e.g., native C method).*"
            next
          end

          # Add a note if the method is defined in an included module
          if File.expand_path(source_file) != File.expand_path(file_path)
            output_lines << "*Note: Method defined in `#{Rails.root.join(source_file).relative_path_from(Rails.root)}`*"
            output_lines << ""
          end

          # Read all lines from the *correct* source file
          all_file_lines = File.readlines(source_file)
          # Get the relevant lines, starting from the method definition
          method_code_lines = all_file_lines[(start_line - 1)..-1] # -1 for 0-indexing

          code_block = []
          def_line = method_code_lines.first
          # Get the indentation of the 'def' line
          def_indent = def_line[/^(\s*)/, 1].length

          code_block << def_line.strip # Add the 'def' line

          # Iterate over the *rest* of the lines
          method_code_lines[1..-1].each do |line|
            stripped_line = line.strip
            code_block << stripped_line

            # Stop when we find the 'end' keyword at the same
            # indentation level as the 'def' line.
            if stripped_line == "end" && line[/^(\s*)/, 1].length == def_indent
              break # We found the matching 'end'
            end
          end

          output_lines << "```ruby"
          output_lines << code_block.join("\n")
          output_lines << "```"

        rescue StandardError => e
          output_lines << "*Error extracting source for `#{action}`: #{e.message}*"
        end
        output_lines << "" # Add a newline
      end
    end

    # Print the final result to stdout
    puts output_lines.join("\n")

    # Add a final message to stderr (so it doesn't end up in the file)
    warn "\n✅ Pundit documentation generation complete."
    warn "Tip: Pipe this output to a file:"
    warn "  bundle exec rake docs:pundit > PUNDIT_DOCS.md"
  end
end
