require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

=begin

RSpec.describe "/parties/tax_ids", type: :request do

  # This should return the minimal set of attributes required to create a valid
  # Parties::TaxId. As you add validations to Parties::TaxId, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Parties::TaxId.create! valid_attributes
      get _parties_tax_ids_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      tax_id = Parties::TaxId.create! valid_attributes
      get _parties_tax_id_url(tax_id)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new__parties_tax_id_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      tax_id = Parties::TaxId.create! valid_attributes
      get edit__parties_tax_id_url(tax_id)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Parties::TaxId" do
        expect {
          post _parties_tax_ids_url, params: { parties_tax_id: valid_attributes }
        }.to change(Parties::TaxId, :count).by(1)
      end

      it "redirects to the created parties_tax_id" do
        post _parties_tax_ids_url, params: { parties_tax_id: valid_attributes }
        expect(response).to redirect_to(_parties_tax_id_url(Parties::TaxId.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Parties::TaxId" do
        expect {
          post _parties_tax_ids_url, params: { parties_tax_id: invalid_attributes }
        }.to change(Parties::TaxId, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post _parties_tax_ids_url, params: { parties_tax_id: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested parties_tax_id" do
        tax_id = Parties::TaxId.create! valid_attributes
        patch _parties_tax_id_url(tax_id), params: { parties_tax_id: new_attributes }
        tax_id.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the parties_tax_id" do
        tax_id = Parties::TaxId.create! valid_attributes
        patch _parties_tax_id_url(tax_id), params: { parties_tax_id: new_attributes }
        tax_id.reload
        expect(response).to redirect_to(parties_tax_id_url(tax_id))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        tax_id = Parties::TaxId.create! valid_attributes
        patch _parties_tax_id_url(tax_id), params: { parties_tax_id: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested parties_tax_id" do
      tax_id = Parties::TaxId.create! valid_attributes
      expect {
        delete _parties_tax_id_url(tax_id)
      }.to change(Parties::TaxId, :count).by(-1)
    end

    it "redirects to the parties_tax_ids list" do
      tax_id = Parties::TaxId.create! valid_attributes
      delete _parties_tax_id_url(tax_id)
      expect(response).to redirect_to(_parties_tax_ids_url)
    end
  end
end
=end
